MUNComputerScienceSociety/MUNCS-Website

content/the_society/executives/contents.lr

Fixed typo in election information on executives page

---

content/contents.lr

Added GitHub link

---

content/blog/A Force-Start into Game Development/contents.lr
content/blog/DOTNET Core - Start of Something Native/contents.lr
content/blog/Hype vs Reality - Intro/contents.lr
content/blog/Introduction to Git for Beginners/contents.lr
content/blog/Landing a CS Internship Part 1 - Intro/contents.lr
content/blog/Landing a CS Internship Part 2 - Job Search/contents.lr
content/blog/Landing a CS Internship Part 3 - Side Projects/contents.lr
content/blog/Take Control of Time with Git - Intermediate Git Tutorial/contents.lr
content/blog/Welcome everyone!/contents.lr
content/blog/contents.lr
templates/layout.html

Migrates all existing posts from the old blog, *mostly* intact, so the old blog can be shut down.

Migrate blog from wordpress to github pages

---

assets/static/css/page-content.css
assets/static/css/simple-sidebar.css

- Format unminified css files in `/assets`
- Fix size of header image, as per the lovely images below:
to
Hi Riley

Format css, fix header image size

---

content/contents.lr

Reverts MUNComputerScienceSociety/Website#36

Revert "Added test message to test deploying"

---

content/resources/contents.lr
content/resources/workshops/gamedev/contents.lr

fixed some _broke_ links, added a _missing_ link

Add new redirect zip file and link in /resources

---

README.md
content/blog/contents.lr
databags/posts.json
databags/posts.schema.json
new_post.py
scripts/new_post.py
templates/blog.html

* Created a JSON file and associated JSON schema to contain a list of all blog posts
* Made blog index dynamically generate the page from said JSON file
* Created a script to automatically create the necessary folder structure for a new post and to add the new post to the JSON file

Streamlined blog process

---

content/contents.lr
content/resources/workshops/gamedev/contents.lr

* Added link to workshops on homepage
* Removed Slack announcement, and moved that to "join us"
* Added link to video for gamedev workshop 1
* Did some miscellaneous cleanup, such as correcting markdown style violations

Improved workshop pages

---

content/contents.lr
content/the_society/apply/contents.lr
content/the_society/executives/contents.lr

- Remove old execs
- Add links on the mainpage/exec. page linking to the new apply page
- Content of the apply page is pretty bare since most of the information is found in the forms link

Add links and info about applying to the exec

---

assets/static/css/page-content.css
content/contents.lr
content/events/2019/contents.lr
content/events/2019/march_rapid/contents.lr
content/events/contents.lr
content/the_society/contents.lr
templates/layout.html

New event, _chess time_
Made css of the sidebar components smaller

Add March Rapid events

---

content/events/2019/march_rapid/contents.lr

Inserted facebook link into March Rapid event page.
First pr btw. ;)

Added facebook event link.

---

content/the_society/constitution/contents.lr

- Updated membership criteria
- Members are now people enrolled in compsci courses, or compsci alumni
- Added new positions
- Executive Assistant
- Event Coordinator
- Academic Officer
- Technology Officer
- Updated executive requirements
- Students who *plan* to declare a compsci major are now eligible to be an executive
- Updated Executive Assistant/Secretary duties
- No longer responsible for social media and email
- Renamed social representative to event coordinator
- Added social representative
- Added academic officer
- Added technology officer
- Added sports coordinator
- Added responsibility to Representative-at-Large
- Also responsible for assisting with day-to-day operations
- Updated election due date
- Now the last day of the winter semester
- Changed the voting system to be …

Updated constitution

---

content/the_society/constitution/contents.lr

Executive did not sign off on the change of the constitution (yet).
_kyle doesn't know how github works_
Reverts MUNComputerScienceSociety/Website#57

Revert "Updated constitution"

---

content/the_society/constitution/contents.lr

- Updated membership criteria
- Members are now people enrolled in compsci courses, or compsci alumni
- Added new positions
- Executive Assistant
- Event Coordinator
- Academic Officer
- Technology Officer
- Updated executive requirements
- Students who *plan* to declare a compsci major are now eligible to be an executive
- Updated Executive Assistant/Secretary duties
- No longer responsible for social media and email
- Renamed social representative to event coordinator
- Added social representative
- Added academic officer
- Added technology officer
- Added sports coordinator
- Added responsibility to Representative-at-Large
- Also responsible for assisting with day-to-day operations
- Updated election due date
- Now the last day of the winter semester
- Changed the voting system to be …

Re-added new constitution

---

templates/layout.html

Added links to the site sidebar to our meeting minutes and agendas

Added meeting minutes and meeting agenda links

---

content/resources/tutorials/contents.lr

Added a link to the tutorials page to our tutorial content folder on the society's mun site.

Added link to tutorial content

---

content/the_society/code_of_conduct/contents.lr
templates/layout.html

Added the [Community Covenant](https://community-covenant.net/) code of conduct to the site.

Added code of conduct

---

content/blog/Welcome everyone!/contents.lr
content/contents.lr
templates/layout.html

pls review then merge k thx bye

discord time

---

content/the_society/executives/contents.lr

Updated exec list

---

content/contents.lr

gotta have that insta on the _go_

Add instagram to homepage

---

content/events/2019/contents.lr
content/events/2019/xonotic_lan/contents.lr
content/events/contents.lr

make sure to review commands and dates and such, poster to soon follow!

Xonotic lan

---

content/events/2020/contents.lr
content/events/2020/python_n_ladders_II/contents.lr
content/events/2020/xonotic_lan_2/contents.lr
content/events/contents.lr

add xonotic-lan-2 event page

---

content/events/2020/contents.lr
content/events/2020/xonotic_lan_2_v2/contents.lr
content/events/contents.lr

xonotic_lan_II_v2

---

content/the_society/constitution/contents.lr

- consistent lack of case on bullet points
- International Students pep.
- Academic rep.
- Sports rep.
---

2020 consitiution update, new roles, consistent downcase

---

content/the_society/executives/contents.lr

Executives Names Change

---

content/the_society/executives/contents.lr

Minor Changes

---

content/events/2020/contents.lr
content/events/2020/networking_event/contents.lr
content/events/contents.lr

Everything is done, but I still need to figure out how to upload new posters to our mun cs directory and then add one to the bottom of the event page. If there's any resources on how to do that please point me in that direction!

added content, still needs poster

---

src/pages/society/locations.astro

Hey,
There was a small typo on the locations page. I changed the room number that is under construction from ER 2036 to EN 2036.
Cheers,
Amin

Fixed typo in locations page

---

src/pages/society/locations.astro

Hey folks,
I deleted the opacity CSS for EN 2036 (slab). 
Happy Hactoberfest :) 
Cheers,
Amin

Changed the opacity of slab EN 2036

---

src/pages/events/advent-of-code-2022.md
tailwind.config.js

this is more to test out the new cloudflare pages preview deployments :)

aoc more proper green text

---

src/components/Event.jsx
src/data/events.js
src/pages/events/october-2022-job-opportunities-in-iot-security-testing.md

"Job Opportunities in IoT Security Testing" event page

---

src/pages/society/constitution.md

1. Replace the role of Social Representative with two new roles: Outreach Coordinator and Marketing Officer.
2. Replace Representative-At-Large and First Year Representative with a new, non-voting role: Society Volunteer
3. Remove the role of Hack Frost Rep (Madison, head of Hack Frost, has suggested that it is no longer necessary).
4. Add the role of Executive Alumni, a non-voting role for former members of the exec who wish to remain in an advisory capacity. We already have this unofficially (Honourary Executive).
5. Allow any member of the society to be appointed to an empty role, with preference given to Society Volunteers
1. Add a definition of a “Voting Role”: any role except Society Volunteer and Executive Alumni would be allowed to vote in meetings.
2. Remove the role of …

2023 constitution update, role changes, misc. small updates and fixes
